apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pv-access
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
