apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pv-access-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: pv-access
  apiGroup: rbac.authorization.k8s.io
