name: Deploy to Minikube

on:
  push:
    branches:
      - env/staging
      - main

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.TOKEN }}

    - name: Build Inventory Image
      run: |
        docker build . --tag ghcr.io/dmitryd435/coffee-api:latest
        docker push ghcr.io/dmitryd435/coffee-api:latest

    - name: Check Minikube status
      run: |
        minikube status
  
    - name: Use Minikube context
      run: |
        kubectl config use-context minikube

    - name: Create or update Kubernetes ConfigMap
      run: |
        kubectl create configmap postgres-config \
        --from-literal=POSTGRES_DB=${{ secrets.DB_NAME }} \
        --from-literal=POSTGRES_USER=${{ secrets.DB_USER }} \
        --from-literal=POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
        --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to Minikube
      run: |
        kubectl apply -f .kubernetes --validate=false



        


        




